#!/usr/bin/env bash

function I3-GAPS()
{
    sudo pacman -S i3-gaps i3status dmenu ttf-dejavu xorg xorg-xinit xterm pipewire pipewire-alsa pipewire-pulse pipewire-jack pavucontrol \
    zsh wget ranger lynx avahi bluez bluez-utils openssh acpi acpid lxappearance arandr --noconfirm
    #cp /etc/X11/xinit/xinitrc ~/.xinitrc
    #sed -i '/exec/,/twm/ s/^/#/' ~/.xinitrc
    echo "exec i3" >> ~/.xinitrc
    autostart="if [[ -z \$DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
        exec startx
    fi"
    echo "$autostart" >> ~/.bashrc
    systemctl enable NetworkManager
    systemctl enable avahi
    systemctl enable sshd
    systemctl enable bluetooth
    systemctl enable acpid
    reboot
}
I3-GAPS    