#!/bin/bash

if whiptail --title "Do you want to Install Yay-git?" --yesno "Yay is a Helper, used to manage packages in AUR repositories" 10 50
then
   [ $? == 0 ] && which yay || which git || sudo pacman -S git --noconfirm && git clone http://aur.archlinux.org/yay-git && cd yay-git && makepkg -si
   echo "Yay Instaled!"
else
   exit 1
fi
