#!/bin/bash

whiptail --title "Do you want to Install Yay-git?" --yesno "Yay is a Helper, used to manage packages in AUR repositories" 10 50
case $? in
   0) which yay && echo "YAY Installed" && exit 0
      which git || sudo pacman -S git --noconfirm
      cd /tmp
      git clone http://aur.archlinux.org/yay-git
      cd yay-git
      makepkg -si --noconfirm
      rm -rf /tmp/yay-git
      exit 0
   ;;
    1) exit 0 
   ;;
  esac


